# Generated by Django 2.2 on 2022-07-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='farm_base.Owner', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipality'),
        ),
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State'),
        ),
    ]
