# Generated by Django 2.2 on 2022-07-24 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_base', '0002_auto_20220724_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_base.Owner'),
        ),
    ]
